### ISSUE TITLE
40k 10e App Collaboration

### ISSUE THREAD

**Issue by fordepowers** [tabletop-json/w40k.10e#1]

**Comment by tabletopJson** [comment]
Hi @fordepowers, thanks for reaching out. Sorry for the delay on responding to this, it would appear this accounts notifications are not set up correctly.

This project is specifically focused on providing data in a usable format for 10e 40k, in order for other groups/developers to consume said data to power their projects. The dataset is free to use, as hosting is effectively handled by GitHub. If you want to use the dataset please feel free to do so.

The folks over at https://app.armyreactor.com/ are already using our data to power such an application as you've suggested, if that helps?
